[package]
name = "toggle"
version = "0.1.0"
edition = "2021"
authors = ["Steve Morin"]
description = "A CLI tool for toggling code comments across multiple languages"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
