#ifndef TOGL_H
#define TOGL_H

#pragma once

/* Generated by cbindgen. Do not edit by hand. Regenerated by build.rs. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI version for runtime negotiation. Bump on any breaking C-ABI change.
 */
#define TOGL_ABI_VERSION 1

#define TOGL_OK 0

#define TOGL_ERR_NULL_POINTER -1

#define TOGL_ERR_INVALID_UTF8 -2

#define TOGL_ERR_PANIC -3

#define TOGL_ERR_OPERATION -4

#define TOGL_ERR_INVALID_ARGUMENT -5

/**
 * A line range `[start, end]`, 1-based inclusive. Frozen POD — never change layout.
 */
typedef struct {
  uintptr_t start;
  uintptr_t end;
} ToglRange;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Crate version as a static NUL-terminated string (never freed by the caller).
 */
const char *togl_version(void);

/**
 * Integer ABI version for runtime negotiation.
 */
uint32_t togl_abi_version(void);

/**
 * Human-readable message for a status code (static; do not free).
 */
const char *togl_error_message(int code);

/**
 * Free a `char*` previously returned by this library via an out-pointer.
 * Safe to call with NULL. Never call C `free()` on togl strings.
 */
void togl_string_free(char *s);

/**
 * Discover sections in `content`; returns a JSON array of `{id,desc,start_line,end_line}`.
 */
int togl_discover_sections(const char *content, char **out_json);

/**
 * Scan `content` (labeled by `path`); returns a JSON array of scan-section records.
 */
int togl_scan_sections(const char *path, const char *content, char **out_json);

/**
 * Validate `content`; returns a JSON array of check issues. `pair_only != 0` enables pair mode.
 */
int togl_validate_sections(const char *content, int pair_only, char **out_json);

/**
 * Toggle line-comment markers on the given 1-based inclusive ranges.
 */
int togl_toggle_comments(const char *content,
                         const ToglRange *ranges,
                         uintptr_t range_count,
                         int force_mode,
                         char **out_result);

/**
 * Toggle the comment state of a named `toggle:start`/`toggle:end` section.
 */
int togl_find_and_toggle_section(const char *content,
                                 const char *section_id,
                                 const char *comment_marker,
                                 char **out_result);

/**
 * Activate one variant of a group, commenting out its siblings.
 */
int togl_activate_variant(const char *content,
                          const char *group,
                          const char *variant,
                          const char *comment_marker,
                          char **out_result);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TOGL_H */
